FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
COPY target/cosmicdoc-auth-service-0.0.1-SNAPSHOT.jar app.jar
ENV SPRING_PROFILES_ACTIVE=prod
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
